In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
!pip install xlrd

Requirement already satisfied: xlrd in c:\users\kasianova_anna\anaconda3\lib\site-packages (2.0.1)

Выгрузка и чтение датасет X_1

In [2]:
X_1_xlsx = 'E:\Data10\X_1.xlsx'

In [3]:
X_1 = pd.read_excel(X_1_xlsx, engine = 'openpyxl')

Проверка размерности датасета

In [4]:
X_1.shape

(18433, 32)

Вывод первых 5 строк датасета X_1

In [5]:
print(X_1.head())

          ID                                       NAME  PARENT_ID      LOGIN  \
0        NaN                                        NaN        NaN        NaN
1  1500923.0      Дом по адресу Красковская ул., д.121А        NaN         WS
2  1500933.0   Дом по адресу Байкальская ул., д.18, к.2        NaN         WS
3  1500943.0          Дом по адресу Перовская ул., д.48        NaN         WS
4  1500951.0  Дом по адресу Парковая 3-я ул., д.39, к.3        NaN  404070001

      COL_754              COL_755        COL_756            COL_757  \
0  Назначение  Форма собственности  Год постройки  Год реконструкции
1         NaN                  NaN           1956                NaN
2         NaN                  NaN           2005                NaN
3         NaN                  NaN           1955                NaN
4         NaN                  NaN           1960                NaN

         COL_758            COL_759  ...                    COL_775  \
0  Серия проекта  Количество этажей  ...  Очередность уборки кровли
1        2048798                  1  ...                        NaN
2        2048798                 18  ...                        NaN
3        2048912                  4  ...                   22289162
4        2048912                  5  ...                   22289162

           COL_781 COL_782                 COL_2156             COL_2463  \
0  Материал кровли    UNOM  Вид социального объекта  Тип жилищного фонда
1         22289204   49928                      NaN             22741963
2         22289201   64148                      NaN             42875644
3         22289204   19485                      NaN             42875644
4         22289201   18533                      NaN             42875644

     COL_3163               COL_3243                    COL_3363  \
0  Статус МКД  Статус управления МКД  Количество грузовых лифтов
1    58761330                    NaN                           0
2    58761330               45063584                           0
3    58761330               45063584                           0
4    58761330               45063584                           0

                        COL_3468     COL_103506
0  Причина Изменения Статуса МКД  Категория МКД
1                            NaN            NaN
2                            NaN            NaN
3                            NaN            NaN
4                            NaN            NaN

[5 rows x 32 columns]

Вывод общей информации о X_1

In [6]:
X_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18433 entries, 0 to 18432
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          18432 non-null  float64
 1   NAME        18432 non-null  object
 2   PARENT_ID   22 non-null     float64
 3   LOGIN       18432 non-null  object
 4   COL_754     4156 non-null   object
 5   COL_755     1 non-null      object
 6   COL_756     18375 non-null  object
 7   COL_757     2 non-null      object
 8   COL_758     18374 non-null  object
 9   COL_759     18375 non-null  object
 10  COL_760     18354 non-null  object
 11  COL_761     5618 non-null   object
 12  COL_762     18374 non-null  object
 13  COL_763     18356 non-null  object
 14  COL_764     18356 non-null  object
 15  COL_765     715 non-null    object
 16  COL_766     715 non-null    object
 17  COL_767     1 non-null      object
 18  COL_769     18374 non-null  object
 19  COL_770     5674 non-null   object
 20  COL_771     18359 non-null  object
 21  COL_772     18359 non-null  object
 22  COL_775     2129 non-null   object
 23  COL_781     5600 non-null   object
 24  COL_782     18433 non-null  object
 25  COL_2156    1 non-null      object
 26  COL_2463    5848 non-null   object
 27  COL_3163    18433 non-null  object
 28  COL_3243    4584 non-null   object
 29  COL_3363    18354 non-null  object
 30  COL_3468    69 non-null     object
 31  COL_103506  1 non-null      object
dtypes: float64(2), object(30)
memory usage: 4.5+ MB

Подсчет количества пропущенных значений в каждом столбце

In [7]:
X_1.isna().sum()

ID                1
NAME              1
PARENT_ID     18411
LOGIN             1
COL_754       14277
COL_755       18432
COL_756          58
COL_757       18431
COL_758          59
COL_759          58
COL_760          79
COL_761       12815
COL_762          59
COL_763          77
COL_764          77
COL_765       17718
COL_766       17718
COL_767       18432
COL_769          59
COL_770       12759
COL_771          74
COL_772          74
COL_775       16304
COL_781       12833
COL_782           0
COL_2156      18432
COL_2463      12585
COL_3163          0
COL_3243      13849
COL_3363         79
COL_3468      18364
COL_103506    18432
dtype: int64

Количестово значений ноль в каждом столбце

In [8]:
#zero_counts = (X_1 ==0).sum()

In [9]:
#zero_counts = X_1.apply(lambda x: x == 0).sum()

In [10]:
#print(zero_counts)

Выгрузка датасет X_2

In [3]:
X_2_xlsx = 'E:\Data10\X_2.xlsx'

In [4]:
X_2 = pd.read_excel(X_2_xlsx, engine = 'openpyxl')

Проверка размерности

In [163]:
X_2.shape

(1048575, 8)

In [164]:
X_2['Дата создания во внешней системе'] = X_2['Дата создания во внешней системе'].str.extract('(\d{4}-\d{2}-\d{2})')

In [165]:
X_2['Дата создания во внешней системе'] = pd.to_datetime(X_2['Дата создания во внешней системе']).dt.date

Вывод первых 5 строк датасета Х_2

In [166]:
print(X_2.head())

                                   Наименование Источник  \
0                                Открыт колодец      MVK
1  Отклонение ГВС ниже нормы ночью (мониторинг)    ASUPR
2   Отклонение ГВС ниже нормы днем (мониторинг)    ASUPR
3                    Температура ГВС ниже нормы    ASUPR
4                    Температура ГВС ниже нормы    ASUPR

  Дата создания во внешней системе               Дата закрытия Округ  \
0                       2022-08-30  2022-08-30 15:40:26.565000   ВАО
1                       2022-02-20  2022-04-04 02:43:22.101000   ВАО
2                       2022-03-07  2022-03-09 09:33:24.894000   ВАО
3                       2022-03-05  2022-03-05 19:14:00.190000   ВАО
4                       2022-02-18  2022-02-18 18:44:14.682000   ВАО

                                               Адрес     unom  \
0  внутригородская территория муниципальный округ...  2115191
1  внутригородская территория муниципальный округ...  2404461
2  внутригородская территория муниципальный округ...  2404461
3  внутригородская территория муниципальный округ...  2404461
4  внутригородская территория муниципальный округ...  2404461

  Дата и время завершения события во
0                                NaN
1                                NaN
2                                NaN
3                                NaN
4                                NaN

Добавить префикс к значению в столбце 'Адрес'

In [167]:

prefix = "Российская Федерация, город Москва, "
X_2['Адрес'] = prefix + X_2['Адрес']

Вывод общей информации по X_2

In [168]:
X_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 8 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   Наименование                        1048532 non-null  object
 1   Источник                            1048575 non-null  object
 2   Дата создания во внешней системе    1048575 non-null  object
 3   Дата закрытия                       1048574 non-null  object
 4   Округ                               1048575 non-null  object
 5   Адрес                               1048575 non-null  object
 6   unom                                1048575 non-null  int64
 7   Дата и время завершения события во  302806 non-null   object
dtypes: int64(1), object(7)
memory usage: 64.0+ MB

Высести уникальные значения столбца Наименование

In [210]:
unique_values = X_2['Наименование'].unique()

Для вывода уникальных значений на печать

In [211]:
for value in unique_values:
    print(value)

Открыт колодец
Отклонение ГВС ниже нормы ночью (мониторинг)
Отклонение ГВС ниже нормы днем (мониторинг)
Температура ГВС ниже нормы
Отсутствует циркуляция ГВС
T1 > max
Изменение конфигурации УСПД
Расхождение времени ПУ
Критичное отклонение температуры ГВС ниже нормы днем (мониторинг)
Низкий уровень сигнала GSM
Нет связи с ПУ
Отсутствуют актуальные суточные значения
Отсутствуют актуальные мгновенные значения
Критичное отклонение температуры ГВС ниже нормы ночью (мониторинг)
Нет питания УСПД
Открыт шкаф УСПД
Нет связи с УСПД
Угроза взрыва
Отсутствие освещения в местах общего пользования
Загрязнение/замусоренность подъезда
Повреждение системы электропроводки/щитового оборудования
Повреждение отделочных покрытий пола/стены/ступеней/перил/других элементов
Загрязнение воды
Повреждение элементов входной двери
Повреждение элементов фасада
Отсутствие ХВС в доме
Загрязнение лифта
Неочищенная кровля
Засор мусоропровода
Неисправность запирающего устройства
Отсутствие освещения в лифте
Неудовлетворительное техническое содержание мусоропровода
Лифт требует ремонта
Колодцы, хлопает крышка
Отсутствие ГВС в доме
Аномальное значение разницы температур
Засоры, засор на дворовой сети
T1 < min
Температура в квартире ниже нормативной
Недогрев ГВС
Поломка освещения перед подъездом
Колодцы, люк занижен
Поломка лифта
Повреждение межпанельных швов
Наличие крыс/мышей/насекомых в местах общего пользования
Аварийное повреждение лестницы
Засор канализации
Повреждение внутренней двери
Отсутствие связи
Датчик вибрации
Протечка труб в подъезде
Повреждение кровли
Провал
Колодцы, разрушен асфальт вокруг колодца
Повреждение козырька подъезда
Утечка воды из земли, прочее
Запах газа в доме
Сильная течь в системе отопления
Поломка почтовых ящиков
Запах газа на улице
Подтопление строений
Утечка воды, прочее
Загрязнение/замусоренность козырька
Повреждение инженерных сетей
Разбито/сломано/повреждено окно в местах общего пользования
Запах газа в кухне
Подтопление, течь трубопровода на водомерном узле
Протечка в подъезде
Несовпадение серийного номера ПУ на УСПД
Качество воды - вода с осадком
Подтопление, повреждение водопровода во внутриквартальном коллекторе
Застревание в лифте
Открыт колодец на газоне
Пожар
Колодцы, прочее
Протечка с кровли
Аварийная протечка в подъезде
Аварийная протечка с кровли
Загрязнение окна в местах общего пользования
Загрязнение отделочных покрытий
Неудовлетворительное санитарное содержание мусоропровода
Запах газа от колонки
Утечка воды, течет водопроводная колонка или подводка
Отсутствие отопления в доме
Температура в помещении общего пользования ниже нормативной
Задымление
Отрицательные интегральные значения
Аномальное значение времени наработки
Повреждение пола/стены/ступеней/перил/других элементов
Блокировка входной двери
Нарушение на настенном газопроводе
Течь в системе отопления
Запах газа из закрытой квартиры
Провал на проезжей части
Запах газа в квартире (помещении)
Прорыв теплосети (водопровода)
Утечка воды из колодца, прочее
Запах газа в подъезде
Протечка с балкона/козырька
Пожар; Задымление
Неисправность пожарной сигнализации
Неработоспособность подъемной платформы для инвалидов
Нарушение в работе газового оборудования
Недокомплект пожарного шкафа
Поломка пандуса
Наличие грибка/плесени
Проверить настенный газопровод
Подтопление, вода поступает в котлован строителей
Повреждение/поломка светильника
Подтопление канала теплосети
Утечка воды из-под асфальта, прочее
Изменение канала связи
Нарушение подачи воды, нет воды в здании
Хлопок газа
Аномальное значение объема в обратном трубопроводе
Загрязнение/замусоренность территории
Аномальное значение температуры в подающем трубопроводе
Аномальное значение температуры в обратном трубопроводе
Аномальное значение объема в подающем трубопроводе
Аномальное значение отпущенной тепловой энергии
Аномальное значение массы в подающем трубопроводе
Слабое горение
Наличие надписей/объявлений
Утечка воды из колодца, поступает на проезжую часть
Запах газа в квартире
Загрязнение входной двери
Качество воды - вода с запахом
Колодцы, люк завышен
Подтопление, поступает вода в камеру теплосети
Нарушение подачи воды, не работает водопроводная колонка
Обрушение
Загрязнение/замусоренность подвала/полуподвала
Запах газа от газового оборудования
Запах гари в квартире/подъезде
Загрязнение внутренней двери
Засор на городской сети
Запах в подъезде
Течет вода из колонки.
Подтопление, прочее
Нет газа
Запах газа в холле
Задымление в подъезде
Качество воды - ржавая вода
Нарушение подачи воды, слабое давление
Подтопление приямка ЦТП
Запах газа в подъезде и на улице
Описание отсутствует
Запах газа по вентиляции
Колодцы, провал колодца
Колодцы, нет люка и крышки
Колодцы, люк расколот
Нарушение подачи воды, прочее
Восстановление трубопровода, пневмопробойник
Открыта крышка колодца
Провал на месте старой раскопки
Колодцы, люк сдвинут
nan
Запах газа на улице; Запах газа в доме
Не  работает  АГВ
Взрыв
Засоры, запах
Засоры, прочее
Колодцы на проезжей части, хлопает крышка
Утечка воды из земли, поступает на проезжую часть
Открыт колодец на проезжей части
Запах газа в кухне от стояка
Запах газа с улицы в квартиру
Качество воды - окрашенная вода
Повреждение асфальтобетонного покрытия
P1 <= 0
Нет газа в кваптире
Колодцы, люк на боку
Отсутствует крышка люка
Утечка воды из колодца, поступает в канализацию/водосток
Провалы, прочее
Загазованность крана № Г2 40162 2,6%
Провал на газоне
Гул (шум, вибрация) от газопровода
Запах газа от колодца; Открыт колодец
Подтопление, течь задвижки на водомерном узле
Погас Вечный огонь
Колодцы на проезжей части, провал колодца
Утечка воды, течет спец. вывод
Вибрирует газовая труба
Аномальное значение разницы объемов
Утечка воды из-под асфальта, поступает на проезжую часть
Запах газа в квартире (помещении); Запах газа в доме
Занижен  газ/ковер
просел ковер
P2 <= 0
Запах газа в квартире с улицы
Проверить работу ЭХЗ
Проверить квартиру после пожара
Гул (шум) на объекте АО МОСГАЗ
Провал ковера
Запах газа в кухне; Запах газа от газового оборудования
Провал колодца
Запах газа от стояка
Занижен ковер
Запах газа от колодца
Запах газа от газового оборудования; Запах газа в доме
Запах газа от настенного газопровода
Запах газа в ванной
Иные нарушения
Запах газа в кухне; Запах газа в доме
Нет  газа
Качество воды - мутная вода
Загрязнение почтовых ящиков
Нарушение подачи воды, нет воды в ЦТП
Качество воды, прочее
Провал асфальтобетонного покрытия
Запах газа на улице, в подъезде
Угроза обрушения
Колодцы на проезжей части, разрушен асфальт вокруг колодца
Запах газа в кухне и в холле
Отсутствует крышка колодца
Пожар; Обрушение
Хлопает крышка ковера
Перекрытие полос
Нарушение на настенном газопроводе; Запах газа в квартире (помещении)
Запах газа из подвала
Открыт колодец; Провал
Взрыв; Пожар
Установить дежурство на ГРП № Вешняки кв. 76
Запах газа в частном доме
Колодцы на проезжей части, люк занижен
Восстановление трубопровода, работа по графику
Прорыв теплосети (водопровода); Открыт колодец
Проверить подпор, отключить ГРП № Вешняки, кв.79.
Запах газа в помещении
Нарушение в работе АОГВ
Провал грунта вокруг ковера
Подтопление, вода поступает в городской коллектор (извне)
Колодцы на проезжей части, люк завышен
Подтопление сооружений метрополитена
Запах газа в туалете
Открата крышка ковера
Запах газа в кухне; Запах газа в квартире (помещении)
Нарушение подачи воды, нет воды на верхних этажах
Гремят крышки коверов
Гремит крышка ковера
Повреждение подъемной платформы для инвалидов
Повреждение плиточного/брусчатого покрытия
Нет газа по стояку
Занижен ковер м/г
Аварийная протечка труб в подъезде
Пожар; Запах газа в квартире (помещении)
Нарушение в работе газового оборудования; Запах газа в кухне
Нарушение в работе газового оборудования; Нет газа
Запах газа у АГВ
Завышено давление газа
Пожар; Запах газа в доме
Запах газа от ШБДГ
Запах  газа  на  улице и в подъезде
Запах газа на улице и в квартире
Поврежден настенный газопровод
Подтопление телефонной сети
Запах газа в подъезде и квартире
Запах газа на улице и в подъезде
Гремит  крышка ковера
Открыта крышка колодца (трещит крышка ковера)
стучит крышка ковера
Запах газа в квартире (помещении); Запах газа на улице; Запах газа в доме
Прорыв теплосети (водопровода); Задымление
Запах газа в подъезде и в квартире.
Провал плиточного/брусчатого покрытия
Отсутствует крышка ковера
Нарушение на настенном газопроводе; Гул (шум, вибрация) от газопровода
Взрыв; Пожар; Задымление
Гул (шум) на объекте АО МОСГАЗ; Запах газа на улице
Нарушение на настенном газопроводе; Запах газа в кухне
Запах газа в коллекторе
Запах газа в квартире (помещении); Запах газа от газового оборудования
Колодцы на проезжей части, прочее
Восстановление трубопровода, санация
Восстановление трубопровода, прочее
Не работает колонка.
Запах газа в котельной
Угроза взрыва; Запах газа в доме
Пожар; Запах газа в кухне
Запах газа в подъезде и в квартире
Просадка асфальта( колодец)
Занижен колодец
Запах газа в холле и квартире
Запах газа в частном доме; Запах газа от газового оборудования
Нет газа в квартире
Открыт колодец МГ
Провал грунта
Восстановление трубопровода, просадка грунта на трассе трубопровода
Провис настенный газопровод
Просадка асфальта вокруг колодца
Утечка воды из-под асфальта, поступает в канализацию/водосток
Колодцы на проезжей части, открыт колодец
Провал, промоина
Хлопок газа; Нарушение в работе газового оборудования
Не работает АГВ
Запах газа в доме от АГВ
Нарушение в работе газового оборудования; Слабое горение
Проверить работу ГРП
Утечка воды из земли, поступает в канализацию/водосток
Нет  газа в квартире

In [169]:
print(X_2.head())

                                   Наименование Источник  \
0                                Открыт колодец      MVK
1  Отклонение ГВС ниже нормы ночью (мониторинг)    ASUPR
2   Отклонение ГВС ниже нормы днем (мониторинг)    ASUPR
3                    Температура ГВС ниже нормы    ASUPR
4                    Температура ГВС ниже нормы    ASUPR

  Дата создания во внешней системе               Дата закрытия Округ  \
0                       2022-08-30  2022-08-30 15:40:26.565000   ВАО
1                       2022-02-20  2022-04-04 02:43:22.101000   ВАО
2                       2022-03-07  2022-03-09 09:33:24.894000   ВАО
3                       2022-03-05  2022-03-05 19:14:00.190000   ВАО
4                       2022-02-18  2022-02-18 18:44:14.682000   ВАО

                                               Адрес     unom  \
0  Российская Федерация, город Москва, внутригоро...  2115191
1  Российская Федерация, город Москва, внутригоро...  2404461
2  Российская Федерация, город Москва, внутригоро...  2404461
3  Российская Федерация, город Москва, внутригоро...  2404461
4  Российская Федерация, город Москва, внутригоро...  2404461

  Дата и время завершения события во
0                                NaN
1                                NaN
2                                NaN
3                                NaN
4                                NaN

In [9]:
grouped_X_2= X_2.groupby('unom')['Наименование'].size().reset_index(name='Инциндент')

In [10]:
print(grouped_X_2)

         unom  Инциндент
0         308         29
1         309        540
2         310         33
3         311         23
4         312        155
...       ...        ...
6710  5281829          4
6711  5283529          7
6712  5286357          2
6713  5288995          1
6714  5289239          1

[6715 rows x 2 columns]

In [8]:
grouped.to_excel("E:\Data10\grouped_X_2.xlsx", index=False)

Подсчет количества пропущенных значений в каждом столбце

In [170]:
#X_2.isna().sum()

In [203]:
X_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 8 columns):
 #   Column                              Non-Null Count    Dtype
---  ------                              --------------    -----
 0   Наименование                        1048532 non-null  object
 1   Источник                            1048575 non-null  object
 2   Дата создания во внешней системе    1048575 non-null  object
 3   Дата закрытия                       1048574 non-null  object
 4   Округ                               1048575 non-null  object
 5   Адрес                               1048575 non-null  object
 6   unom                                1048575 non-null  int64
 7   Дата и время завершения события во  302806 non-null   object
dtypes: int64(1), object(7)
memory usage: 64.0+ MB

In [204]:
X_2['Дата создания во внешней системе'] = X_2['Дата создания во внешней системе'].astype(str)

In [209]:
X_2.to_excel('E:\Data10\X_2_11.xlsx', index=False, engine='openpyxl')

Выгрузка датасет X_3

In [12]:
X_3_xlsx = 'E:\Data10\X_3.xlsx'

In [13]:
X_3 = pd.read_excel(X_3_xlsx, engine = 'openpyxl')

Проверка размерности датасета

In [178]:
X_3.shape

(1747, 13)

Вывод первых 5 строк датасета

In [180]:
print(X_3.head())

   global_id  PERIOD                                          WORK_NAME  \
0     351060    2022                      замена лифтового оборудования
1     430496    2022                      замена лифтового оборудования
2     348580    2022  ремонт внутридомовых инженерных систем водоотв...
3     348581    2022  ремонт внутридомовых инженерных систем теплосн...
4     348578    2022  ремонт внутридомовых инженерных систем холодно...

   NUM_ENTRANCE ElevatorNumber PLAN_DATE_START PLAN_DATE_END FACT_DATE_START  \
0           1.0              1      15.07.2022    28.08.2022      27.06.2022
1           1.0              1      30.09.2022    14.10.2022      30.09.2022
2           NaN            NaN      21.02.2022    20.06.2022      01.02.2022
3           NaN            NaN      21.04.2022    10.07.2022      07.05.2022
4           NaN            NaN      21.02.2022    20.06.2022      01.02.2022

  FACT_DATE_END                           AdmArea           District  \
0    14.10.2022  Восточный административный округ  район Богородское
1    21.10.2022  Восточный административный округ  район Богородское
2    25.05.2022  Восточный административный округ  район Богородское
3    03.08.2022  Восточный административный округ  район Богородское
4    27.06.2022  Восточный административный округ  район Богородское

                                             Address   UNOM
0  Российская Федерация, город Москва, внутригоро...  20151
1  Российская Федерация, город Москва, внутригоро...  20151
2  Российская Федерация, город Москва, внутригоро...  11466
3  Российская Федерация, город Москва, внутригоро...  11466
4  Российская Федерация, город Москва, внутригоро...  11466

Вывод общей информации по датасету

In [181]:
X_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1747 entries, 0 to 1746
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   global_id        1747 non-null   int64
 1   PERIOD           1747 non-null   int64
 2   WORK_NAME        1747 non-null   object
 3   NUM_ENTRANCE     285 non-null    float64
 4   ElevatorNumber   285 non-null    object
 5   PLAN_DATE_START  1747 non-null   object
 6   PLAN_DATE_END    1747 non-null   object
 7   FACT_DATE_START  1747 non-null   object
 8   FACT_DATE_END    1747 non-null   object
 9   AdmArea          1747 non-null   object
 10  District         1747 non-null   object
 11  Address          1747 non-null   object
 12  UNOM             1747 non-null   int64
dtypes: float64(1), int64(3), object(9)
memory usage: 177.6+ KB

Преобразование столбец 'Преобразуем столбец ' в формат datetime' в формат datetime

In [1]:
X_3 ['PLAN_DATE_START'] = X_3 ['PLAN_DATE_START'].dt.strftime('%Y-%m-%d')

NameError: name 'X_3' is not defined

In [ ]:
X_3 ['PLAN_DATE_START'] = pd.to_datetime(X_3 ['PLAN_DATE_START'])

Преобразование формата даты в 'YYYY-MM-DD'

In [184]:
X_3 ['PLAN_DATE_START'] = pd.to_datetime(X_3 ['PLAN_DATE_START'])

In [185]:
print(X_3.head())

   global_id  PERIOD                                          WORK_NAME  \
0     351060    2022                      замена лифтового оборудования
1     430496    2022                      замена лифтового оборудования
2     348580    2022  ремонт внутридомовых инженерных систем водоотв...
3     348581    2022  ремонт внутридомовых инженерных систем теплосн...
4     348578    2022  ремонт внутридомовых инженерных систем холодно...

   NUM_ENTRANCE ElevatorNumber PLAN_DATE_START PLAN_DATE_END FACT_DATE_START  \
0           1.0              1      2022-07-15    28.08.2022      27.06.2022
1           1.0              1      2022-09-30    14.10.2022      30.09.2022
2           NaN            NaN      2022-02-21    20.06.2022      01.02.2022
3           NaN            NaN      2022-04-21    10.07.2022      07.05.2022
4           NaN            NaN      2022-02-21    20.06.2022      01.02.2022

  FACT_DATE_END                           AdmArea           District  \
0    14.10.2022  Восточный административный округ  район Богородское
1    21.10.2022  Восточный административный округ  район Богородское
2    25.05.2022  Восточный административный округ  район Богородское
3    03.08.2022  Восточный административный округ  район Богородское
4    27.06.2022  Восточный административный округ  район Богородское

                                             Address   UNOM
0  Российская Федерация, город Москва, внутригоро...  20151
1  Российская Федерация, город Москва, внутригоро...  20151
2  Российская Федерация, город Москва, внутригоро...  11466
3  Российская Федерация, город Москва, внутригоро...  11466
4  Российская Федерация, город Москва, внутригоро...  11466

Переименование столбца "UNOM" в "unom" для объединения с датасетом X_1 по этому столбцу

In [15]:
X_3 = X_3.rename(columns={'UNOM': 'unom'})

Количестов работ на дом - unom

In [16]:
grouped_X_3= X_3.groupby('unom')['WORK_NAME'].size().reset_index(name='Работы_по_кап_ремонту')

In [17]:
print(grouped_X_3)

      unom  Работы_по_кап_ремонту
0      365                     13
1      367                     12
2      370                      1
3      376                      8
4      379                      1
..     ...                    ...
368  82032                      4
369  82033                      7
370  82036                      5
371  82037                      4
372  82038                      4

[373 rows x 2 columns]

In [19]:
grouped_X_3.to_excel("E:\Data10\grouped_X_3.xlsx", index=False)

Переименование столбца "Address" в "Адрес" для объединения с датасетом X_1 по этому столбцу

In [187]:
X_3 = X_3.rename(columns={'Address': 'Адрес'})

Переименование столбца "PLAN_DATE_START" в "Дата создания во внешней системе" для объединения с датасетом X_1 по этому столбцу

In [188]:
X_3 = X_3.rename(columns={'PLAN_DATE_START' : 'Дата создания во внешней системе'})

In [189]:
print(X_3.head())

   global_id  PERIOD                                          WORK_NAME  \
0     351060    2022                      замена лифтового оборудования
1     430496    2022                      замена лифтового оборудования
2     348580    2022  ремонт внутридомовых инженерных систем водоотв...
3     348581    2022  ремонт внутридомовых инженерных систем теплосн...
4     348578    2022  ремонт внутридомовых инженерных систем холодно...

   NUM_ENTRANCE ElevatorNumber Дата создания во внешней системе PLAN_DATE_END  \
0           1.0              1                       2022-07-15    28.08.2022
1           1.0              1                       2022-09-30    14.10.2022
2           NaN            NaN                       2022-02-21    20.06.2022
3           NaN            NaN                       2022-04-21    10.07.2022
4           NaN            NaN                       2022-02-21    20.06.2022

  FACT_DATE_START FACT_DATE_END                           AdmArea  \
0      27.06.2022    14.10.2022  Восточный административный округ
1      30.09.2022    21.10.2022  Восточный административный округ
2      01.02.2022    25.05.2022  Восточный административный округ
3      07.05.2022    03.08.2022  Восточный административный округ
4      01.02.2022    27.06.2022  Восточный административный округ

            District                                              Адрес   unom
0  район Богородское  Российская Федерация, город Москва, внутригоро...  20151
1  район Богородское  Российская Федерация, город Москва, внутригоро...  20151
2  район Богородское  Российская Федерация, город Москва, внутригоро...  11466
3  район Богородское  Российская Федерация, город Москва, внутригоро...  11466
4  район Богородское  Российская Федерация, город Москва, внутригоро...  11466

In [192]:
X_3 ['Дата создания во внешней системе'] = pd.to_datetime(X_3 ['Дата создания во внешней системе'])

In [196]:
X_3['Дата создания во внешней системе'] = X_3['Дата создания во внешней системе'].astype(str)

In [201]:
X_3.to_excel('E:\Data10\X_3_11.xlsx', index=False, engine='openpyxl')

In [202]:
X_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1747 entries, 0 to 1746
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   global_id                         1747 non-null   int64
 1   PERIOD                            1747 non-null   int64
 2   WORK_NAME                         1747 non-null   object
 3   NUM_ENTRANCE                      285 non-null    float64
 4   ElevatorNumber                    285 non-null    object
 5   Дата создания во внешней системе  1747 non-null   object
 6   PLAN_DATE_END                     1747 non-null   object
 7   FACT_DATE_START                   1747 non-null   object
 8   FACT_DATE_END                     1747 non-null   object
 9   AdmArea                           1747 non-null   object
 10  District                          1747 non-null   object
 11  Адрес                             1747 non-null   object
 12  unom                              1747 non-null   int64
dtypes: float64(1), int64(3), object(9)
memory usage: 177.6+ KB

Подсчет количества пропущенных значений в каждом столбце

In [87]:
#X_3.isna().sum()

Выгрузка датасет X_4.1

In [88]:
X_4_1_xlsx = 'E:\Data10\X_4.1.xlsx'

Строк с индексом  1 назначено в качестве заголовком, т.к стр. инд.0 - пустая

In [89]:
X_4_1 = pd.read_excel(X_4_1_xlsx, header=1)

Проверка размерности датасета

In [90]:
X_4_1.shape

(29, 7)

Вывод первых 5 строк датасета

In [91]:
print(X_4_1.head())

   №\nп/п  Код                                       Наименование  \
0       1  105                              строительный контроль
1       2   26  ремонт подъездов, направленный на восстановлен...
2       3    9  ремонт фасада (замена оконных блоков, располож...
3       4  104  проведение экспертизы проектной документации п...
4       5   20                  разработка проектной документации

  Наименование объекта общего имущества Тип работ   Группа работ  \
0                 Строительный контроль    Услуга  Стройконтроль
1                               Подъезд    Работа            СМР
2                  Фасад(оконные блоки)    Работа            СМР
3                 проведение экспертизы    Услуга            СМР
4     разработка проектной документации    Услуга            СМР

  Сокращенное наименование работы
0                              СК
1                         Подъезд
2                            Окна
3           проведение экспертизы
4                             ПСД

Вывод общей информации по датасетй\у

In [92]:
X_4_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 7 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   №
п/п                                  29 non-null     int64
 1   Код                                    29 non-null     int64
 2   Наименование                           29 non-null     object
 3   Наименование объекта общего имущества  29 non-null     object
 4   Тип работ                              29 non-null     object
 5   Группа работ                           29 non-null     object
 6   Сокращенное наименование работы        29 non-null     object
dtypes: int64(2), object(5)
memory usage: 1.7+ KB

Подсчет количества пропущенных значений в каждом столбце

In [93]:
X_4_1.isna().sum()

№\nп/п                                   0
Код                                      0
Наименование                             0
Наименование объекта общего имущества    0
Тип работ                                0
Группа работ                             0
Сокращенное наименование работы          0
dtype: int64

Выгрузка датасет X_4.2

In [94]:
X_4_2_xlsx = 'E:\Data10\X_4.2.xlsx'

In [95]:
X_4_2 = pd.read_excel(X_4_2_xlsx, engine = 'openpyxl')

Проверка размерности датасета

In [96]:
X_4_2.shape

(498, 16)

Вывод первых 5 строк датасета

In [97]:
print(X_4_2.head())

        ID                                               NAME  PARENT_ID  \
0  3682661                   Ремонт кровельного покрытия дома   26352880
1  3682664                              Ремонт мусоропроводов   26352883
2  3682666  Ремонт электрооборудования (эл. щитков, замена...   26352883
3  3682669  Снятие показаний общедомового прибора учета (е...   26352866
4  3682671                         Техническая инвентаризация   26352866

       LOGIN COL_1044  COL_1045 COL_1157 COL_1239  COL_4488  COL_4489  \
0  migration      NaN       NaN     Иное      4.8       NaN       NaN
1  migration      NaN       NaN     Иное     5.24       NaN       NaN
2  migration      NaN       NaN     Иное  5.24.16       NaN       NaN
3  migration      NaN       NaN     Иное     13.4       NaN       NaN
4  migration      NaN       NaN     Иное     13.4       NaN       NaN

   COL_4764  COL_4923  COL_20060  COL_20061  COL_20062  COL_20063
0         1      2015          0          0        NaN        NaN
1         1      2015          0          0        NaN        NaN
2         1      2015          0          0        NaN        NaN
3         1      2015          0          0        NaN        NaN
4         1      2015          0          0        NaN        NaN

Вывод общей информации по датасету

In [98]:
X_4_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 498 entries, 0 to 497
Data columns (total 16 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ID         498 non-null    int64
 1   NAME       498 non-null    object
 2   PARENT_ID  498 non-null    int64
 3   LOGIN      498 non-null    object
 4   COL_1044   375 non-null    object
 5   COL_1045   384 non-null    float64
 6   COL_1157   313 non-null    object
 7   COL_1239   498 non-null    object
 8   COL_4488   200 non-null    float64
 9   COL_4489   167 non-null    float64
 10  COL_4764   498 non-null    int64
 11  COL_4923   498 non-null    int64
 12  COL_20060  498 non-null    int64
 13  COL_20061  498 non-null    int64
 14  COL_20062  168 non-null    float64
 15  COL_20063  185 non-null    float64
dtypes: float64(5), int64(6), object(5)
memory usage: 62.4+ KB

Подсчет количества пропущенных значений в каждом столбце

In [99]:
X_4_2.isna().sum()

ID             0
NAME           0
PARENT_ID      0
LOGIN          0
COL_1044     123
COL_1045     114
COL_1157     185
COL_1239       0
COL_4488     298
COL_4489     331
COL_4764       0
COL_4923       0
COL_20060      0
COL_20061      0
COL_20062    330
COL_20063    313
dtype: int64

Выгрузка и чтерние датасета

In [100]:
X_5_xlsx = 'E:\Data10\X_5.xlsx'

In [101]:
X_5 = pd.read_excel(X_5_xlsx, engine = 'openpyxl')

Проверка размерности датасета

In [102]:
X_5.shape

(950, 3)

Вывод первых 5 строк датасета

In [103]:
print(X_5.head())

                                     id  \
0  001b91e9-2ac5-4949-bff0-bb51d4f3057c
1  0089fd48-aa7a-443d-85a5-00470285b076
2  016697a2-feef-4568-9629-3c9dddae3aea
3  02212d7e-3c4c-4e6a-8f6b-d4f8f1b82e72
4  0250d455-608a-4d63-9902-ebe3b82d0b67

                                             name   system
0                         Нарушение в работе  АГВ  MOS_GAS
1  Проверить на загазованность дюкер Гольяновский  MOS_GAS
2   Разрушение асфальтового полотна вокруг ковера  MOS_GAS
3                Угроза взрыва; Запах газа в доме  MOS_GAS
4                               Запах газа от ГРП  MOS_GAS

Вывод общей информации по датасету

In [104]:
X_5.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      950 non-null    object
 1   name    949 non-null    object
 2   system  950 non-null    object
dtypes: object(3)
memory usage: 22.4+ KB

Подсчет количества пропущенных значений в каждом столбце

In [105]:
X_5.isna().sum()

id        0
name      1
system    0
dtype: int64

In [106]:
X_5.nunique()

id        950
name      791
system     10
dtype: int64

Объединение двух датасет  X_2 и X_3 по стообецу  unmo.

In [107]:
#Merged_X_2_3 = X_2.merge(X_3, on='unom', how='inner')

In [205]:
Merged_X_2_3 =pd.merge(X_2, X_3, on=['unom', 'Дата создания во внешней системе'])

In [206]:
Merged_X_2_3.head()

,Наименование,Источник,Дата создания во внешней системе,Дата закрытия,Округ,Адрес_x,unom,Дата и время завершения события во,global_id,PERIOD,WORK_NAME,NUM_ENTRANCE,ElevatorNumber,PLAN_DATE_END,FACT_DATE_START,FACT_DATE_END,AdmArea,District,Адрес_y
0,Повреждение внутренней двери,EDC,2022-04-21,2022-04-21 21:24:52.502000,ВАО,"Российская Федерация, город Москва, внутригоро...",19980,NaN,394968,2022,ремонт внутридомовых инженерных систем теплосн...,NaN,NaN,10.07.2022,21.03.2022,07.06.2022,Восточный административный округ,район Перово,"Российская Федерация, город Москва, внутригоро..."
1,Расхождение времени ПУ,ASUPR,2022-05-21,2022-05-20 22:52:42.222000,ВАО,"Российская Федерация, город Москва, внутригоро...",26890,NaN,366087,2022,"ремонт подвальных помещений, относящихся к общ...",NaN,NaN,30.09.2022,13.04.2022,17.06.2022,Восточный административный округ,район Гольяново,"Российская Федерация, город Москва, внутригоро..."
2,Лифт требует ремонта,EDC,2022-05-21,2023-04-05 01:00:33.987000,ВАО,"Российская Федерация, город Москва, внутригоро...",19211,NaN,352186,2022,ремонт крыши,NaN,NaN,10.09.2022,12.05.2022,18.10.2022,Восточный административный округ,район Восточное Измайлово,"Российская Федерация, город Москва, внутригоро..."
3,Поломка почтовых ящиков,EDC,2022-05-21,2022-05-23 16:53:30.502000,ВАО,"Российская Федерация, город Москва, внутригоро...",19211,NaN,352186,2022,ремонт крыши,NaN,NaN,10.09.2022,12.05.2022,18.10.2022,Восточный административный округ,район Восточное Измайлово,"Российская Федерация, город Москва, внутригоро..."
4,Низкий уровень сигнала GSM,ASUPR,2022-05-21,2022-05-21 02:34:53.929000,ВАО,"Российская Федерация, город Москва, внутригоро...",19211,NaN,352186,2022,ремонт крыши,NaN,NaN,10.09.2022,12.05.2022,18.10.2022,Восточный административный округ,район Восточное Измайлово,"Российская Федерация, город Москва, внутригоро..."

In [207]:
Merged_X_2_3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1323 entries, 0 to 1322
Data columns (total 19 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Наименование                        1323 non-null   object
 1   Источник                            1323 non-null   object
 2   Дата создания во внешней системе    1323 non-null   object
 3   Дата закрытия                       1323 non-null   object
 4   Округ                               1323 non-null   object
 5   Адрес_x                             1323 non-null   object
 6   unom                                1323 non-null   int64
 7   Дата и время завершения события во  513 non-null    object
 8   global_id                           1323 non-null   int64
 9   PERIOD                              1323 non-null   int64
 10  WORK_NAME                           1323 non-null   object
 11  NUM_ENTRANCE                        330 non-null    float64
 12  ElevatorNumber                      330 non-null    object
 13  PLAN_DATE_END                       1323 non-null   object
 14  FACT_DATE_START                     1323 non-null   object
 15  FACT_DATE_END                       1323 non-null   object
 16  AdmArea                             1323 non-null   object
 17  District                            1323 non-null   object
 18  Адрес_y                             1323 non-null   object
dtypes: float64(1), int64(3), object(15)
memory usage: 206.7+ KB

In [208]:
Merged_X_2_3.to_excel('E:\Data10\Merged_X_2_31.xlsx', index=False, engine='openpyxl')

In [ ]:
J

In [20]:
merged_Grouped_X_2_3 = grouped_X_2.merge(grouped_X_3, on='unom', how='outer') 
merged_Grouped_X_2_3.fillna(0, inplace=True)

In [21]:
merged_Grouped_X_2_3.to_excel("E:\Data10\merged_Grouped_X_2_3.xlsx", index=False)